<?php

namespace Yoosuf\Document\Documents\Support;

final class ErrorCodes
{
    public const VALIDATION_ERROR = 'VALIDATION_ERROR';
    public const TEMPLATE_NOT_FOUND = 'TEMPLATE_NOT_FOUND';
    public const AMBIGUOUS_TEMPLATE_SELECTION = 'AMBIGUOUS_TEMPLATE_SELECTION';
    public const UNSUPPORTED_OUTPUT_FORMAT = 'UNSUPPORTED_OUTPUT_FORMAT';
    public const TEMPLATE_RENDER_ERROR = 'TEMPLATE_RENDER_ERROR';
    public const CONVERSION_UNAVAILABLE = 'CONVERSION_UNAVAILABLE';
    public const DOCUMENT_CONVERSION_ERROR = 'DOCUMENT_CONVERSION_ERROR';
    public const DOCUMENT_STORAGE_ERROR = 'DOCUMENT_STORAGE_ERROR';
    public const DOCUMENT_NOT_FOUND = 'DOCUMENT_NOT_FOUND';
    public const DOCUMENT_NOT_READY = 'DOCUMENT_NOT_READY';
    public const INVALID_DOCUMENT_STATUS = 'INVALID_DOCUMENT_STATUS';
    public const SALES_ORDER_NOT_FOUND = 'SALES_ORDER_NOT_FOUND';
    public const DOCUMENT_MODEL_NOT_SUPPORTED = 'DOCUMENT_MODEL_NOT_SUPPORTED';
    public const IDEMPOTENCY_KEY_CONFLICT = 'IDEMPOTENCY_KEY_CONFLICT';
    public const HTTP_ERROR = 'HTTP_ERROR';
}
